use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

/// Enum representing various Arm64 ISA extensions and architecture profiles.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Arm64ISA {
    None,
    Aes,
    Bf16,
    Brbe,
    Bti,
    Btie,
    Cmpbr,
    Cpa,
    Crc,
    Crypto,
    Cssc,
    D128,
    Dit,
    Dotprod,
    F16f32dot,
    F16f32mm,
    F16mm,
    F32mm,
    F64mm,
    F8f16mm,
    F8f32mm,
    Faminmax,
    Fcma,
    Flagm,
    Fp,
    Fp16,
    Fp16fml,
    Fp8,
    Fp8dot2,
    Fp8dot4,
    Fp8fma,
    Fprcvt,
    Gcie,
    Gcs,
    Hbc,
    Hinte,
    I8mm,
    Ite,
    Jscvt,
    Ls64,
    Lscp,
    Lse,
    Lse128,
    Lsfe,
    Lsui,
    Lut,
    Memtag,
    Mops,
    MopsGo,
    Mtetc,
    Occmo,
    Pauth,
    PauthLr,
    Pmuv3,
    Poe2,
    Pops,
    Predres,
    Predres2,
    Profile,
    Ras,
    Rasv2,
    Rcpc,
    Rcpc3,
    Rdm,
    Rng,
    Sb,
    Sha2,
    Sha3,
    Simd,
    Sm4,
    Sme,
    SmeB16b16,
    SmeF16f16,
    SmeF64f64,
    SmeF8f16,
    SmeF8f32,
    SmeFa64,
    SmeI16i64,
    SmeLutv2,
    SmeMop4,
    SmeTmop,
    Sme2,
    Sme2p1,
    Sme2p2,
    Sme2p3,
    Ssbs,
    SsveAes,
    SsveBitperm,
    SsveFexpa,
    SsveFp8dot2,
    SsveFp8dot4,
    SsveFp8fma,
    Sve,
    SveAes,
    SveAes2,
    SveB16b16,
    SveB16mm,
    SveBfscale,
    SveBitperm,
    SveF16f32mm,
    SveSha3,
    SveSm4,
    Sve2,
    Sve2Aes,
    Sve2Bitperm,
    Sve2Sha3,
    Sve2Sm4,
    Sve2p1,
    Sve2p2,
    Sve2p3,
    Tev,
    The,
    Tlbid,
    Tlbiw,
    Wfxt,
}

impl fmt::Display for Arm64ISA {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl Arm64ISA {
    pub fn as_str(&self) -> &'static str {
        match self {
            Arm64ISA::None => "none",
            Arm64ISA::Aes => "aes",
            Arm64ISA::Bf16 => "bf16",
            Arm64ISA::Brbe => "brbe",
            Arm64ISA::Bti => "bti",
            Arm64ISA::Btie => "btie",
            Arm64ISA::Cmpbr => "cmpbr",
            Arm64ISA::Cpa => "cpa",
            Arm64ISA::Crc => "crc",
            Arm64ISA::Crypto => "crypto",
            Arm64ISA::Cssc => "cssc",
            Arm64ISA::D128 => "d128",
            Arm64ISA::Dit => "dit",
            Arm64ISA::Dotprod => "dotprod",
            Arm64ISA::F16f32dot => "f16f32dot",
            Arm64ISA::F16f32mm => "f16f32mm",
            Arm64ISA::F16mm => "f16mm",
            Arm64ISA::F32mm => "f32mm",
            Arm64ISA::F64mm => "f64mm",
            Arm64ISA::F8f16mm => "f8f16mm",
            Arm64ISA::F8f32mm => "f8f32mm",
            Arm64ISA::Faminmax => "faminmax",
            Arm64ISA::Fcma => "fcma",
            Arm64ISA::Flagm => "flagm",
            Arm64ISA::Fp => "fp",
            Arm64ISA::Fp16 => "fp16",
            Arm64ISA::Fp16fml => "fp16fml",
            Arm64ISA::Fp8 => "fp8",
            Arm64ISA::Fp8dot2 => "fp8dot2",
            Arm64ISA::Fp8dot4 => "fp8dot4",
            Arm64ISA::Fp8fma => "fp8fma",
            Arm64ISA::Fprcvt => "fprcvt",
            Arm64ISA::Gcie => "gcie",
            Arm64ISA::Gcs => "gcs",
            Arm64ISA::Hbc => "hbc",
            Arm64ISA::Hinte => "hinte",
            Arm64ISA::I8mm => "i8mm",
            Arm64ISA::Ite => "ite",
            Arm64ISA::Jscvt => "jscvt",
            Arm64ISA::Ls64 => "ls64",
            Arm64ISA::Lscp => "lscp",
            Arm64ISA::Lse => "lse",
            Arm64ISA::Lse128 => "lse128",
            Arm64ISA::Lsfe => "lsfe",
            Arm64ISA::Lsui => "lsui",
            Arm64ISA::Lut => "lut",
            Arm64ISA::Memtag => "memtag",
            Arm64ISA::Mops => "mops",
            Arm64ISA::MopsGo => "mops-go",
            Arm64ISA::Mtetc => "mtetc",
            Arm64ISA::Occmo => "occmo",
            Arm64ISA::Pauth => "pauth",
            Arm64ISA::PauthLr => "pauth-lr",
            Arm64ISA::Pmuv3 => "pmuv3",
            Arm64ISA::Poe2 => "poe2",
            Arm64ISA::Pops => "pops",
            Arm64ISA::Predres => "predres",
            Arm64ISA::Predres2 => "predres2",
            Arm64ISA::Profile => "profile",
            Arm64ISA::Ras => "ras",
            Arm64ISA::Rasv2 => "rasv2",
            Arm64ISA::Rcpc => "rcpc",
            Arm64ISA::Rcpc3 => "rcpc3",
            Arm64ISA::Rdm => "rdm",
            Arm64ISA::Rng => "rng",
            Arm64ISA::Sb => "sb",
            Arm64ISA::Sha2 => "sha2",
            Arm64ISA::Sha3 => "sha3",
            Arm64ISA::Simd => "simd",
            Arm64ISA::Sm4 => "sm4",
            Arm64ISA::Sme => "sme",
            Arm64ISA::SmeB16b16 => "sme-b16b16",
            Arm64ISA::SmeF16f16 => "sme-f16f16",
            Arm64ISA::SmeF64f64 => "sme-f64f64",
            Arm64ISA::SmeF8f16 => "sme-f8f16",
            Arm64ISA::SmeF8f32 => "sme-f8f32",
            Arm64ISA::SmeFa64 => "sme-fa64",
            Arm64ISA::SmeI16i64 => "sme-i16i64",
            Arm64ISA::SmeLutv2 => "sme-lutv2",
            Arm64ISA::SmeMop4 => "sme-mop4",
            Arm64ISA::SmeTmop => "sme-tmop",
            Arm64ISA::Sme2 => "sme2",
            Arm64ISA::Sme2p1 => "sme2p1",
            Arm64ISA::Sme2p2 => "sme2p2",
            Arm64ISA::Sme2p3 => "sme2p3",
            Arm64ISA::Ssbs => "ssbs",
            Arm64ISA::SsveAes => "ssve-aes",
            Arm64ISA::SsveBitperm => "ssve-bitperm",
            Arm64ISA::SsveFexpa => "ssve-fexpa",
            Arm64ISA::SsveFp8dot2 => "ssve-fp8dot2",
            Arm64ISA::SsveFp8dot4 => "ssve-fp8dot4",
            Arm64ISA::SsveFp8fma => "ssve-fp8fma",
            Arm64ISA::Sve => "sve",
            Arm64ISA::SveAes => "sve-aes",
            Arm64ISA::SveAes2 => "sve-aes2",
            Arm64ISA::SveB16b16 => "sve-b16b16",
            Arm64ISA::SveB16mm => "sve-b16mm",
            Arm64ISA::SveBfscale => "sve-bfscale",
            Arm64ISA::SveBitperm => "sve-bitperm",
            Arm64ISA::SveF16f32mm => "sve-f16f32mm",
            Arm64ISA::SveSha3 => "sve-sha3",
            Arm64ISA::SveSm4 => "sve-sm4",
            Arm64ISA::Sve2 => "sve2",
            Arm64ISA::Sve2Aes => "sve2-aes",
            Arm64ISA::Sve2Bitperm => "sve2-bitperm",
            Arm64ISA::Sve2Sha3 => "sve2-sha3",
            Arm64ISA::Sve2Sm4 => "sve2-sm4",
            Arm64ISA::Sve2p1 => "sve2p1",
            Arm64ISA::Sve2p2 => "sve2p2",
            Arm64ISA::Sve2p3 => "sve2p3",
            Arm64ISA::Tev => "tev",
            Arm64ISA::The => "the",
            Arm64ISA::Tlbid => "tlbid",
            Arm64ISA::Tlbiw => "tlbiw",
            Arm64ISA::Wfxt => "wfxt",
        }
    }

    pub fn all() -> &'static [Arm64ISA] {
        &[
            Arm64ISA::Aes,
            Arm64ISA::Bf16,
            Arm64ISA::Brbe,
            Arm64ISA::Bti,
            Arm64ISA::Btie,
            Arm64ISA::Cmpbr,
            Arm64ISA::Cpa,
            Arm64ISA::Crc,
            Arm64ISA::Crypto,
            Arm64ISA::Cssc,
            Arm64ISA::D128,
            Arm64ISA::Dit,
            Arm64ISA::Dotprod,
            Arm64ISA::F16f32dot,
            Arm64ISA::F16f32mm,
            Arm64ISA::F16mm,
            Arm64ISA::F32mm,
            Arm64ISA::F64mm,
            Arm64ISA::F8f16mm,
            Arm64ISA::F8f32mm,
            Arm64ISA::Faminmax,
            Arm64ISA::Fcma,
            Arm64ISA::Flagm,
            Arm64ISA::Fp,
            Arm64ISA::Fp16,
            Arm64ISA::Fp16fml,
            Arm64ISA::Fp8,
            Arm64ISA::Fp8dot2,
            Arm64ISA::Fp8dot4,
            Arm64ISA::Fp8fma,
            Arm64ISA::Fprcvt,
            Arm64ISA::Gcie,
            Arm64ISA::Gcs,
            Arm64ISA::Hbc,
            Arm64ISA::Hinte,
            Arm64ISA::I8mm,
            Arm64ISA::Ite,
            Arm64ISA::Jscvt,
            Arm64ISA::Ls64,
            Arm64ISA::Lscp,
            Arm64ISA::Lse,
            Arm64ISA::Lse128,
            Arm64ISA::Lsfe,
            Arm64ISA::Lsui,
            Arm64ISA::Lut,
            Arm64ISA::Memtag,
            Arm64ISA::Mops,
            Arm64ISA::MopsGo,
            Arm64ISA::Mtetc,
            Arm64ISA::Occmo,
            Arm64ISA::Pauth,
            Arm64ISA::PauthLr,
            Arm64ISA::Pmuv3,
            Arm64ISA::Poe2,
            Arm64ISA::Pops,
            Arm64ISA::Predres,
            Arm64ISA::Predres2,
            Arm64ISA::Profile,
            Arm64ISA::Ras,
            Arm64ISA::Rasv2,
            Arm64ISA::Rcpc,
            Arm64ISA::Rcpc3,
            Arm64ISA::Rdm,
            Arm64ISA::Rng,
            Arm64ISA::Sb,
            Arm64ISA::Sha2,
            Arm64ISA::Sha3,
            Arm64ISA::Simd,
            Arm64ISA::Sm4,
            Arm64ISA::Sme,
            Arm64ISA::SmeB16b16,
            Arm64ISA::SmeF16f16,
            Arm64ISA::SmeF64f64,
            Arm64ISA::SmeF8f16,
            Arm64ISA::SmeF8f32,
            Arm64ISA::SmeFa64,
            Arm64ISA::SmeI16i64,
            Arm64ISA::SmeLutv2,
            Arm64ISA::SmeMop4,
            Arm64ISA::SmeTmop,
            Arm64ISA::Sme2,
            Arm64ISA::Sme2p1,
            Arm64ISA::Sme2p2,
            Arm64ISA::Sme2p3,
            Arm64ISA::Ssbs,
            Arm64ISA::SsveAes,
            Arm64ISA::SsveBitperm,
            Arm64ISA::SsveFexpa,
            Arm64ISA::SsveFp8dot2,
            Arm64ISA::SsveFp8dot4,
            Arm64ISA::SsveFp8fma,
            Arm64ISA::Sve,
            Arm64ISA::SveAes,
            Arm64ISA::SveAes2,
            Arm64ISA::SveB16b16,
            Arm64ISA::SveB16mm,
            Arm64ISA::SveBfscale,
            Arm64ISA::SveBitperm,
            Arm64ISA::SveF16f32mm,
            Arm64ISA::SveSha3,
            Arm64ISA::SveSm4,
            Arm64ISA::Sve2,
            Arm64ISA::Sve2Aes,
            Arm64ISA::Sve2Bitperm,
            Arm64ISA::Sve2Sha3,
            Arm64ISA::Sve2Sm4,
            Arm64ISA::Sve2p1,
            Arm64ISA::Sve2p2,
            Arm64ISA::Sve2p3,
            Arm64ISA::Tev,
            Arm64ISA::The,
            Arm64ISA::Tlbid,
            Arm64ISA::Tlbiw,
            Arm64ISA::Wfxt,
        ]
    }
}

impl FromStr for Arm64ISA {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let norm = s.to_ascii_lowercase().replace(['_', '.'], "-");
        match norm.as_str() {
            "none" => Ok(Arm64ISA::None),
            "aes" => Ok(Arm64ISA::Aes),
            "bf16" => Ok(Arm64ISA::Bf16),
            "brbe" => Ok(Arm64ISA::Brbe),
            "bti" => Ok(Arm64ISA::Bti),
            "btie" => Ok(Arm64ISA::Btie),
            "cmpbr" => Ok(Arm64ISA::Cmpbr),
            "cpa" => Ok(Arm64ISA::Cpa),
            "crc" | "crc32" => Ok(Arm64ISA::Crc),
            "crypto" => Ok(Arm64ISA::Crypto),
            "cssc" => Ok(Arm64ISA::Cssc),
            "d128" => Ok(Arm64ISA::D128),
            "dit" => Ok(Arm64ISA::Dit),
            "dotprod" => Ok(Arm64ISA::Dotprod),
            "f16f32dot" => Ok(Arm64ISA::F16f32dot),
            "f16f32mm" => Ok(Arm64ISA::F16f32mm),
            "f16mm" => Ok(Arm64ISA::F16mm),
            "f32mm" => Ok(Arm64ISA::F32mm),
            "f64mm" => Ok(Arm64ISA::F64mm),
            "f8f16mm" => Ok(Arm64ISA::F8f16mm),
            "f8f32mm" => Ok(Arm64ISA::F8f32mm),
            "faminmax" => Ok(Arm64ISA::Faminmax),
            "fcma" => Ok(Arm64ISA::Fcma),
            "flagm" => Ok(Arm64ISA::Flagm),
            "fp" => Ok(Arm64ISA::Fp),
            "fp16" => Ok(Arm64ISA::Fp16),
            "fp16fml" | "fhm" => Ok(Arm64ISA::Fp16fml),
            "fp8" => Ok(Arm64ISA::Fp8),
            "fp8dot2" => Ok(Arm64ISA::Fp8dot2),
            "fp8dot4" => Ok(Arm64ISA::Fp8dot4),
            "fp8fma" => Ok(Arm64ISA::Fp8fma),
            "fprcvt" => Ok(Arm64ISA::Fprcvt),
            "gcie" => Ok(Arm64ISA::Gcie),
            "gcs" => Ok(Arm64ISA::Gcs),
            "hbc" => Ok(Arm64ISA::Hbc),
            "hinte" => Ok(Arm64ISA::Hinte),
            "i8mm" => Ok(Arm64ISA::I8mm),
            "ite" => Ok(Arm64ISA::Ite),
            "jscvt" => Ok(Arm64ISA::Jscvt),
            "ls64" => Ok(Arm64ISA::Ls64),
            "lscp" => Ok(Arm64ISA::Lscp),
            "lse" => Ok(Arm64ISA::Lse),
            "lse128" => Ok(Arm64ISA::Lse128),
            "lsfe" => Ok(Arm64ISA::Lsfe),
            "lsui" => Ok(Arm64ISA::Lsui),
            "lut" => Ok(Arm64ISA::Lut),
            "memtag" | "mte" => Ok(Arm64ISA::Memtag),
            "mops" => Ok(Arm64ISA::Mops),
            "mops-go" => Ok(Arm64ISA::MopsGo),
            "mtetc" => Ok(Arm64ISA::Mtetc),
            "occmo" => Ok(Arm64ISA::Occmo),
            "pauth" => Ok(Arm64ISA::Pauth),
            "pauth-lr" => Ok(Arm64ISA::PauthLr),
            "pmuv3" => Ok(Arm64ISA::Pmuv3),
            "poe2" => Ok(Arm64ISA::Poe2),
            "pops" => Ok(Arm64ISA::Pops),
            "predres" | "specres" => Ok(Arm64ISA::Predres),
            "predres2" | "specres2" => Ok(Arm64ISA::Predres2),
            "profile" | "spe" => Ok(Arm64ISA::Profile),
            "ras" => Ok(Arm64ISA::Ras),
            "rasv2" => Ok(Arm64ISA::Rasv2),
            "rcpc" | "lrcpc" => Ok(Arm64ISA::Rcpc),
            "rcpc3" | "lrcpc3" => Ok(Arm64ISA::Rcpc3),
            "rdm" => Ok(Arm64ISA::Rdm),
            "rng" => Ok(Arm64ISA::Rng),
            "sb" => Ok(Arm64ISA::Sb),
            "sha2" | "sha1" | "sha256" => Ok(Arm64ISA::Sha2),
            "sha3" | "sha512" => Ok(Arm64ISA::Sha3),
            "simd" | "advsimd" | "neon" => Ok(Arm64ISA::Simd),
            "sm4" => Ok(Arm64ISA::Sm4),
            "sme" => Ok(Arm64ISA::Sme),
            "sme-b16b16" => Ok(Arm64ISA::SmeB16b16),
            "sme-f16f16" => Ok(Arm64ISA::SmeF16f16),
            "sme-f64f64" => Ok(Arm64ISA::SmeF64f64),
            "sme-f8f16" => Ok(Arm64ISA::SmeF8f16),
            "sme-f8f32" => Ok(Arm64ISA::SmeF8f32),
            "sme-fa64" => Ok(Arm64ISA::SmeFa64),
            "sme-i16i64" => Ok(Arm64ISA::SmeI16i64),
            "sme-lutv2" => Ok(Arm64ISA::SmeLutv2),
            "sme-mop4" => Ok(Arm64ISA::SmeMop4),
            "sme-tmop" => Ok(Arm64ISA::SmeTmop),
            "sme2" => Ok(Arm64ISA::Sme2),
            "sme2p1" => Ok(Arm64ISA::Sme2p1),
            "sme2p2" => Ok(Arm64ISA::Sme2p2),
            "sme2p3" => Ok(Arm64ISA::Sme2p3),
            "ssbs" => Ok(Arm64ISA::Ssbs),
            "ssve-aes" => Ok(Arm64ISA::SsveAes),
            "ssve-bitperm" => Ok(Arm64ISA::SsveBitperm),
            "ssve-fexpa" => Ok(Arm64ISA::SsveFexpa),
            "ssve-fp8dot2" => Ok(Arm64ISA::SsveFp8dot2),
            "ssve-fp8dot4" => Ok(Arm64ISA::SsveFp8dot4),
            "ssve-fp8fma" => Ok(Arm64ISA::SsveFp8fma),
            "sve" => Ok(Arm64ISA::Sve),
            "sve-aes" => Ok(Arm64ISA::SveAes),
            "sve-aes2" => Ok(Arm64ISA::SveAes2),
            "sve-b16b16" => Ok(Arm64ISA::SveB16b16),
            "sve-b16mm" => Ok(Arm64ISA::SveB16mm),
            "sve-bfscale" => Ok(Arm64ISA::SveBfscale),
            "sve-bitperm" => Ok(Arm64ISA::SveBitperm),
            "sve-f16f32mm" => Ok(Arm64ISA::SveF16f32mm),
            "sve-sha3" => Ok(Arm64ISA::SveSha3),
            "sve-sm4" => Ok(Arm64ISA::SveSm4),
            "sve2" => Ok(Arm64ISA::Sve2),
            "sve2-aes" => Ok(Arm64ISA::Sve2Aes),
            "sve2-bitperm" => Ok(Arm64ISA::Sve2Bitperm),
            "sve2-sha3" => Ok(Arm64ISA::Sve2Sha3),
            "sve2-sm4" => Ok(Arm64ISA::Sve2Sm4),
            "sve2p1" => Ok(Arm64ISA::Sve2p1),
            "sve2p2" => Ok(Arm64ISA::Sve2p2),
            "sve2p3" => Ok(Arm64ISA::Sve2p3),
            "tev" => Ok(Arm64ISA::Tev),
            "the" => Ok(Arm64ISA::The),
            "tlbid" => Ok(Arm64ISA::Tlbid),
            "tlbiw" => Ok(Arm64ISA::Tlbiw),
            "wfxt" => Ok(Arm64ISA::Wfxt),
            other => Err(format!("Unknown Arm64 ISA extension: {}", other)),
        }
    }
}

