use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

/// Enum representing Instruction Set Architecture (ISA) extensions for the x86_64 architecture.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum X64ISA {
    None,
    Adx,
    Aes,
    AmxAvx512,
    AmxBf16,
    AmxComplex,
    AmxFp16,
    AmxFp8,
    AmxInt8,
    AmxMovrs,
    AmxTf32,
    AmxTile,
    Apxf,
    Avx,
    Avx10_1,
    Avx10_2,
    Avx2,
    Avx512bf16,
    Avx512bitalg,
    Avx512bw,
    Avx512bmm,
    Avx512cd,
    Avx512dq,
    Avx512f,
    Avx512fp16,
    Avx512ifma,
    Avx512vbmi,
    Avx512vbmi2,
    Avx512vl,
    Avx512vnni,
    Avx512vp2intersect,
    Avx512vpopcntdq,
    Avxifma,
    Avxneconvert,
    Avxvnni,
    Avxvnniint16,
    Avxvnniint8,
    Bmi,
    Bmi2,
    Cldemote,
    Clflushopt,
    Clwb,
    Clzero,
    Cmpccxadd,
    Crc32,
    Cx16,
    Enqcmd,
    F16c,
    Fma,
    Fma4,
    Fsgsbase,
    Fxsr,
    Gfni,
    Kl,
    Lwp,
    Lzcnt,
    Movbe,
    Movdir64b,
    Movdiri,
    Movrs,
    Mwaitx,
    Pclmul,
    Pku,
    Popcnt,
    Prefetchi,
    Prfchw,
    Ptwrite,
    Raoint,
    Rdpid,
    Rdpru,
    Rdrnd,
    Rdseed,
    Rtm,
    Sahf,
    Serialize,
    Sgx,
    Sha,
    Sha512,
    Sm4,
    Sse,
    Sse2,
    Sse3,
    Sse4_1,
    Sse4_2,
    Sse4a,
    Ssse3,
    Tbm,
    Tsxldtrk,
    Uintr,
    Usermsr,
    Vaes,
    Vpclmulqdq,
    Vzeroupper,
    Waitpkg,
    Aeskl,
    Widekl,
    Xop,
    Xsave,
    Xsavec,
    Xsaveopt,
    Xsaves,
}

impl fmt::Display for X64ISA {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl X64ISA {
    pub fn as_str(&self) -> &'static str {
        match self {
            X64ISA::None => "none",
            X64ISA::Adx => "adx",
            X64ISA::Aes => "aes",
            X64ISA::AmxAvx512 => "amx-avx512",
            X64ISA::AmxBf16 => "amx-bf16",
            X64ISA::AmxComplex => "amx-complex",
            X64ISA::AmxFp16 => "amx-fp16",
            X64ISA::AmxFp8 => "amx-fp8",
            X64ISA::AmxInt8 => "amx-int8",
            X64ISA::AmxMovrs => "amx-movrs",
            X64ISA::AmxTf32 => "amx-tf32",
            X64ISA::AmxTile => "amx-tile",
            X64ISA::Apxf => "apxf",
            X64ISA::Avx => "avx",
            X64ISA::Avx10_1 => "avx10.1",
            X64ISA::Avx10_2 => "avx10.2",
            X64ISA::Avx2 => "avx2",
            X64ISA::Avx512bf16 => "avx512bf16",
            X64ISA::Avx512bitalg => "avx512bitalg",
            X64ISA::Avx512bw => "avx512bw",
            X64ISA::Avx512bmm => "avx512bmm",
            X64ISA::Avx512cd => "avx512cd",
            X64ISA::Avx512dq => "avx512dq",
            X64ISA::Avx512f => "avx512f",
            X64ISA::Avx512fp16 => "avx512fp16",
            X64ISA::Avx512ifma => "avx512ifma",
            X64ISA::Avx512vbmi => "avx512vbmi",
            X64ISA::Avx512vbmi2 => "avx512vbmi2",
            X64ISA::Avx512vl => "avx512vl",
            X64ISA::Avx512vnni => "avx512vnni",
            X64ISA::Avx512vp2intersect => "avx512vp2intersect",
            X64ISA::Avx512vpopcntdq => "avx512vpopcntdq",
            X64ISA::Avxifma => "avxifma",
            X64ISA::Avxneconvert => "avxneconvert",
            X64ISA::Avxvnni => "avxvnni",
            X64ISA::Avxvnniint16 => "avxvnniint16",
            X64ISA::Avxvnniint8 => "avxvnniint8",
            X64ISA::Bmi => "bmi",
            X64ISA::Bmi2 => "bmi2",
            X64ISA::Cldemote => "cldemote",
            X64ISA::Clflushopt => "clflushopt",
            X64ISA::Clwb => "clwb",
            X64ISA::Clzero => "clzero",
            X64ISA::Cmpccxadd => "cmpccxadd",
            X64ISA::Crc32 => "crc32",
            X64ISA::Cx16 => "cx16",
            X64ISA::Enqcmd => "enqcmd",
            X64ISA::F16c => "f16c",
            X64ISA::Fma => "fma",
            X64ISA::Fma4 => "fma4",
            X64ISA::Fsgsbase => "fsgsbase",
            X64ISA::Fxsr => "fxsr",
            X64ISA::Gfni => "gfni",
            X64ISA::Kl => "kl",
            X64ISA::Lwp => "lwp",
            X64ISA::Lzcnt => "lzcnt",
            X64ISA::Movbe => "movbe",
            X64ISA::Movdir64b => "movdir64b",
            X64ISA::Movdiri => "movdiri",
            X64ISA::Movrs => "movrs",
            X64ISA::Mwaitx => "mwaitx",
            X64ISA::Pclmul => "pclmul",
            X64ISA::Pku => "pku",
            X64ISA::Popcnt => "popcnt",
            X64ISA::Prefetchi => "prefetchi",
            X64ISA::Prfchw => "prfchw",
            X64ISA::Ptwrite => "ptwrite",
            X64ISA::Raoint => "raoint",
            X64ISA::Rdpid => "rdpid",
            X64ISA::Rdpru => "rdpru",
            X64ISA::Rdrnd => "rdrnd",
            X64ISA::Rdseed => "rdseed",
            X64ISA::Rtm => "rtm",
            X64ISA::Sahf => "sahf",
            X64ISA::Serialize => "serialize",
            X64ISA::Sgx => "sgx",
            X64ISA::Sha => "sha",
            X64ISA::Sha512 => "sha512",
            X64ISA::Sm4 => "sm4",
            X64ISA::Sse => "sse",
            X64ISA::Sse2 => "sse2",
            X64ISA::Sse3 => "sse3",
            X64ISA::Sse4_1 => "sse4.1",
            X64ISA::Sse4_2 => "sse4.2",
            X64ISA::Sse4a => "sse4a",
            X64ISA::Ssse3 => "ssse3",
            X64ISA::Tbm => "tbm",
            X64ISA::Tsxldtrk => "tsxldtrk",
            X64ISA::Uintr => "uintr",
            X64ISA::Usermsr => "usermsr",
            X64ISA::Vaes => "vaes",
            X64ISA::Vpclmulqdq => "vpclmulqdq",
            X64ISA::Vzeroupper => "vzeroupper",
            X64ISA::Waitpkg => "waitpkg",
            X64ISA::Aeskl => "aeskl",
            X64ISA::Widekl => "widekl",
            X64ISA::Xop => "xop",
            X64ISA::Xsave => "xsave",
            X64ISA::Xsavec => "xsavec",
            X64ISA::Xsaveopt => "xsaveopt",
            X64ISA::Xsaves => "xsaves",
        }
    }

    pub fn all() -> &'static [X64ISA] {
        &[
            X64ISA::Adx,
            X64ISA::Aes,
            X64ISA::AmxAvx512,
            X64ISA::AmxBf16,
            X64ISA::AmxComplex,
            X64ISA::AmxFp16,
            X64ISA::AmxFp8,
            X64ISA::AmxInt8,
            X64ISA::AmxMovrs,
            X64ISA::AmxTf32,
            X64ISA::AmxTile,
            X64ISA::Apxf,
            X64ISA::Avx,
            X64ISA::Avx10_1,
            X64ISA::Avx10_2,
            X64ISA::Avx2,
            X64ISA::Avx512bf16,
            X64ISA::Avx512bitalg,
            X64ISA::Avx512bw,
            X64ISA::Avx512bmm,
            X64ISA::Avx512cd,
            X64ISA::Avx512dq,
            X64ISA::Avx512f,
            X64ISA::Avx512fp16,
            X64ISA::Avx512ifma,
            X64ISA::Avx512vbmi,
            X64ISA::Avx512vbmi2,
            X64ISA::Avx512vl,
            X64ISA::Avx512vnni,
            X64ISA::Avx512vp2intersect,
            X64ISA::Avx512vpopcntdq,
            X64ISA::Avxifma,
            X64ISA::Avxneconvert,
            X64ISA::Avxvnni,
            X64ISA::Avxvnniint16,
            X64ISA::Avxvnniint8,
            X64ISA::Bmi,
            X64ISA::Bmi2,
            X64ISA::Cldemote,
            X64ISA::Clflushopt,
            X64ISA::Clwb,
            X64ISA::Clzero,
            X64ISA::Cmpccxadd,
            X64ISA::Crc32,
            X64ISA::Cx16,
            X64ISA::Enqcmd,
            X64ISA::F16c,
            X64ISA::Fma,
            X64ISA::Fma4,
            X64ISA::Fsgsbase,
            X64ISA::Fxsr,
            X64ISA::Gfni,
            X64ISA::Kl,
            X64ISA::Lwp,
            X64ISA::Lzcnt,
            X64ISA::Movbe,
            X64ISA::Movdir64b,
            X64ISA::Movdiri,
            X64ISA::Movrs,
            X64ISA::Mwaitx,
            X64ISA::Pclmul,
            X64ISA::Pku,
            X64ISA::Popcnt,
            X64ISA::Prefetchi,
            X64ISA::Prfchw,
            X64ISA::Ptwrite,
            X64ISA::Raoint,
            X64ISA::Rdpid,
            X64ISA::Rdpru,
            X64ISA::Rdrnd,
            X64ISA::Rdseed,
            X64ISA::Rtm,
            X64ISA::Sahf,
            X64ISA::Serialize,
            X64ISA::Sgx,
            X64ISA::Sha,
            X64ISA::Sha512,
            X64ISA::Sm4,
            X64ISA::Sse,
            X64ISA::Sse2,
            X64ISA::Sse3,
            X64ISA::Sse4_1,
            X64ISA::Sse4_2,
            X64ISA::Sse4a,
            X64ISA::Ssse3,
            X64ISA::Tbm,
            X64ISA::Tsxldtrk,
            X64ISA::Uintr,
            X64ISA::Usermsr,
            X64ISA::Vaes,
            X64ISA::Vpclmulqdq,
            X64ISA::Vzeroupper,
            X64ISA::Waitpkg,
            X64ISA::Aeskl,
            X64ISA::Widekl,
            X64ISA::Xop,
            X64ISA::Xsave,
            X64ISA::Xsavec,
            X64ISA::Xsaveopt,
            X64ISA::Xsaves,
        ]
    }
}

impl FromStr for X64ISA {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let norm = s.to_ascii_lowercase().replace(['-', '.'], "_");
        match norm.as_str() {
            "none" => Ok(X64ISA::None),
            "adx" => Ok(X64ISA::Adx),
            "aes" => Ok(X64ISA::Aes),
            "amx_avx512" => Ok(X64ISA::AmxAvx512),
            "amx_bf16" => Ok(X64ISA::AmxBf16),
            "amx_complex" => Ok(X64ISA::AmxComplex),
            "amx_fp16" => Ok(X64ISA::AmxFp16),
            "amx_fp8" => Ok(X64ISA::AmxFp8),
            "amx_int8" => Ok(X64ISA::AmxInt8),
            "amx_movrs" => Ok(X64ISA::AmxMovrs),
            "amx_tf32" => Ok(X64ISA::AmxTf32),
            "amx_tile" => Ok(X64ISA::AmxTile),
            "apxf" | "apx_f" => Ok(X64ISA::Apxf),
            "avx" => Ok(X64ISA::Avx),
            "avx10_1" | "avx10_1_512" | "avx10_1_256" => Ok(X64ISA::Avx10_1),
            "avx10_2" | "avx10_2_512" | "avx10_2_256" => Ok(X64ISA::Avx10_2),
            "avx2" => Ok(X64ISA::Avx2),
            "avx512bf16" => Ok(X64ISA::Avx512bf16),
            "avx512bitalg" => Ok(X64ISA::Avx512bitalg),
            "avx512bw" => Ok(X64ISA::Avx512bw),
            "avx512bmm" => Ok(X64ISA::Avx512bmm),
            "avx512cd" => Ok(X64ISA::Avx512cd),
            "avx512dq" => Ok(X64ISA::Avx512dq),
            "avx512f" => Ok(X64ISA::Avx512f),
            "avx512fp16" => Ok(X64ISA::Avx512fp16),
            "avx512ifma" => Ok(X64ISA::Avx512ifma),
            "avx512vbmi" => Ok(X64ISA::Avx512vbmi),
            "avx512vbmi2" => Ok(X64ISA::Avx512vbmi2),
            "avx512vl" => Ok(X64ISA::Avx512vl),
            "avx512vnni" => Ok(X64ISA::Avx512vnni),
            "avx512vp2intersect" => Ok(X64ISA::Avx512vp2intersect),
            "avx512vpopcntdq" => Ok(X64ISA::Avx512vpopcntdq),
            "avxifma" => Ok(X64ISA::Avxifma),
            "avxneconvert" | "avx_ne_convert" => Ok(X64ISA::Avxneconvert),
            "avxvnni" | "avx_vnni" => Ok(X64ISA::Avxvnni),
            "avxvnniint16" | "avx_vnni_int16" => Ok(X64ISA::Avxvnniint16),
            "avxvnniint8" | "avx_vnni_int8" => Ok(X64ISA::Avxvnniint8),
            "bmi" | "bmi1" => Ok(X64ISA::Bmi),
            "bmi2" => Ok(X64ISA::Bmi2),
            "cldemote" => Ok(X64ISA::Cldemote),
            "clflushopt" => Ok(X64ISA::Clflushopt),
            "clwb" => Ok(X64ISA::Clwb),
            "clzero" => Ok(X64ISA::Clzero),
            "cmpccxadd" => Ok(X64ISA::Cmpccxadd),
            "crc32" => Ok(X64ISA::Crc32),
            "cx16" => Ok(X64ISA::Cx16),
            "enqcmd" => Ok(X64ISA::Enqcmd),
            "f16c" => Ok(X64ISA::F16c),
            "fma" | "fma3" => Ok(X64ISA::Fma),
            "fma4" => Ok(X64ISA::Fma4),
            "fsgsbase" => Ok(X64ISA::Fsgsbase),
            "fxsr" => Ok(X64ISA::Fxsr),
            "gfni" => Ok(X64ISA::Gfni),
            "kl" => Ok(X64ISA::Kl),
            "lwp" => Ok(X64ISA::Lwp),
            "lzcnt" | "abm" => Ok(X64ISA::Lzcnt),
            "movbe" => Ok(X64ISA::Movbe),
            "movdir64b" => Ok(X64ISA::Movdir64b),
            "movdiri" => Ok(X64ISA::Movdiri),
            "movrs" => Ok(X64ISA::Movrs),
            "mwaitx" => Ok(X64ISA::Mwaitx),
            "pclmul" | "pclmulqdq" => Ok(X64ISA::Pclmul),
            "pku" => Ok(X64ISA::Pku),
            "popcnt" => Ok(X64ISA::Popcnt),
            "prefetchi" => Ok(X64ISA::Prefetchi),
            "prfchw" | "prefetchw" => Ok(X64ISA::Prfchw),
            "ptwrite" => Ok(X64ISA::Ptwrite),
            "raoint" => Ok(X64ISA::Raoint),
            "rdpid" => Ok(X64ISA::Rdpid),
            "rdpru" => Ok(X64ISA::Rdpru),
            "rdrnd" | "rdrand" => Ok(X64ISA::Rdrnd),
            "rdseed" => Ok(X64ISA::Rdseed),
            "rtm" => Ok(X64ISA::Rtm),
            "sahf" => Ok(X64ISA::Sahf),
            "serialize" => Ok(X64ISA::Serialize),
            "sgx" => Ok(X64ISA::Sgx),
            "sha" => Ok(X64ISA::Sha),
            "sha512" => Ok(X64ISA::Sha512),
            "sm4" => Ok(X64ISA::Sm4),
            "sse" => Ok(X64ISA::Sse),
            "sse2" => Ok(X64ISA::Sse2),
            "sse3" => Ok(X64ISA::Sse3),
            "sse4_1" | "sse41" => Ok(X64ISA::Sse4_1),
            "sse4_2" | "sse42" => Ok(X64ISA::Sse4_2),
            "sse4a" => Ok(X64ISA::Sse4a),
            "ssse3" => Ok(X64ISA::Ssse3),
            "tbm" => Ok(X64ISA::Tbm),
            "tsxldtrk" => Ok(X64ISA::Tsxldtrk),
            "uintr" => Ok(X64ISA::Uintr),
            "usermsr" | "user_msr" => Ok(X64ISA::Usermsr),
            "vaes" => Ok(X64ISA::Vaes),
            "vpclmulqdq" => Ok(X64ISA::Vpclmulqdq),
            "vzeroupper" => Ok(X64ISA::Vzeroupper),
            "waitpkg" => Ok(X64ISA::Waitpkg),
            "aeskl" => Ok(X64ISA::Aeskl),
            "widekl" => Ok(X64ISA::Widekl),
            "xop" => Ok(X64ISA::Xop),
            "xsave" => Ok(X64ISA::Xsave),
            "xsavec" => Ok(X64ISA::Xsavec),
            "xsaveopt" => Ok(X64ISA::Xsaveopt),
            "xsaves" => Ok(X64ISA::Xsaves),
            other => Err(format!("Unknown x64 ISA extension: {}", other)),
        }
    }
}

